logging:
  level:
    ROOT: ERROR
    org.springframework: INFO
    org.springframework.security: INFO
    org.springframework.data: INFO
    org.springframework.web: INFO
    com.verbitsky: ERROR
    com.netflix.eureka: info
    com.netflix.discovery: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/dev/backend.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/dev/application-dev-%d{yyyy-MM-dd}_part.%i.log
      max-file-size: 512KB
      max-history: 3
      clean-history-on-start: true

spring:
  application:
    name: bff-application
  profiles:
    #change it to prod to run in production mode
    active: dev
  config:
    import: "configserver:${CONFIG_SERVER_ADDR}"

